#### 1. Import the numpy package under the name np

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [3]:
dir(np)
print(np.__version__)
np.show_config()

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

limit_output extension: Maximum message size of 10000 exceeded with 10641 characters

#### 3. Create a null vector of size 10

In [4]:
np.full(10,np.nan)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 4. How to find the memory size of any array

In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
Z = np.zeros((10,10),dtype = np.int8)
Z.size
Z.itemsize
Z = np.zeros((10,10),dtype = int)
Z.size
Z.itemsize
print("%d bytes" % (Z.size * Z.itemsize))

100

1

100

4

400 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [6]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [80]:
 np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
print(np.zeros(10))
print(np.full(10,0))
print([0]*10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


#### 7. Create a vector with values ranging from 10 to 49

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last)

In [99]:
Z = np.arange(10)
Z[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [108]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [127]:
a = np.array([1,2,0,0,4,0])
nz = np.nonzero(a)
print(nz)
np.where(a != 0)
a[np.where(a != 0)]

(array([0, 1, 4], dtype=int64),)


(array([0, 1, 4], dtype=int64),)

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix

In [131]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [9]:
np.random.random((3,3,3))

array([[[0.82971563, 0.25002834, 0.86818428],
        [0.98510627, 0.24576948, 0.56243377],
        [0.6573186 , 0.29090324, 0.33340919]],

       [[0.84313231, 0.20495646, 0.38845264],
        [0.61680071, 0.86772226, 0.67475798],
        [0.56612586, 0.48309943, 0.82611863]],

       [[0.65602842, 0.33298927, 0.15075072],
        [0.95818565, 0.08648281, 0.34646184],
        [0.06913452, 0.73019824, 0.14807652]]])

In [10]:
np.info(np.random)
dir(np.random)

Random Number Generation

==================== =========================================================
Utility functions
random_sample        Uniformly distributed floats over ``[0, 1)``.
random               Alias for `random_sample`.
bytes                Uniformly distributed random bytes.
random_integers      Uniformly distributed integers in a given range.
permutation          Randomly permute a sequence / generate a random sequence.
shuffle              Randomly permute a sequence in place.
seed                 Seed the random number generator.
choice               Random sample from 1-D array.

==================== =========================================================

==================== =========================================================
Compatibility functions
rand                 Uniformly distributed values.
randn                Normally distributed values.
ranf                 Uniformly distributed floating point numbers.
randint              Uniformly distribu

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [11]:
Z = np.random.random((1,10))
Z
np.min(Z)
np.max(Z,(0)) # 0 for col and 1 for row

array([[0.25127943, 0.73093681, 0.74175831, 0.70159016, 0.68045467,
        0.50469306, 0.46706501, 0.90551965, 0.52247381, 0.48046958]])

0.2512794267243941

array([0.25127943, 0.73093681, 0.74175831, 0.70159016, 0.68045467,
       0.50469306, 0.46706501, 0.90551965, 0.52247381, 0.48046958])

#### 14. Create a random vector of size 30 and find the mean value

In [166]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.606808222384333


#### 15. Create a 2d array with 1 on the border and 0 inside

In [177]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
Z

Z = np.zeros((5,5))
Z[[0,-1],:] = 1
Z[:,[0,-1]] = 1
Z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [187]:
Z = np.zeros((5,5))
Z_new = np.ones((Z.shape[0] + 2,Z.shape[1]+2))
Z_new[1:-1,1:-1] = Z
Z_new

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [191]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

In [29]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [19]:
np.diag(1+np.arange(4),k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [39]:
Z = np.zeros((8,8))
Z[::2,1::2] = 1
Z[1::2,::2] = 1
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [61]:
np.unravel_index(41,(6,7,8),order = 'F')
np.unravel_index(56,(6,7,8),order = 'C')

(5, 6, 0)

(1, 0, 0)

(0, 5, 1)

'order = C' means python will fill elements with the last axis, for instance, if we got a array with 3 axis python will fill z-axis first.

'order = F' means python will fill elements with the first axis. 

This function default to set order = 'C' type.

#### 21. Create a checkerboard 8x8 matrix using the tile function

In [76]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [209]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.66766785 -1.13930545 -0.80486335 -0.28766686  0.8172911 ]
 [-0.56445679  1.24713782 -1.82410022 -0.60806593  0.30346799]
 [ 0.72079376  0.94544749 -1.7566187   0.80541854  1.02123703]
 [-0.85153534  1.39703123  1.18503504 -0.82148092 -0.54849102]
 [-1.35398806 -0.40169184  0.86259882  1.42168443 -0.43254662]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [233]:
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.uint8,1),
                 ("b",np.uint8,1),
                 ("a",np.uint8,1)])
color
# np.info(np.ubyte) # ubyte = uint8
# np.info(np.dtype)

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [269]:
np.random.seed(1)
a = np.random.rand(5,3)
b = np.random.rand(3,2)
np.dot(a,b)
a @ b
np.dot(np.random.rand(5,3),np.random.rand(3,2))
np.random.rand(5,3) @ np.random.rand(3,2)

array([[0.68206033, 0.27524102],
       [0.3029876 , 0.22070707],
       [0.39654291, 0.44394889],
       [0.73120183, 0.83238604],
       [0.63309939, 0.23052559]])

array([[0.68206033, 0.27524102],
       [0.3029876 , 0.22070707],
       [0.39654291, 0.44394889],
       [0.73120183, 0.83238604],
       [0.63309939, 0.23052559]])

array([[1.35505535, 1.56122134],
       [0.70209969, 1.46616815],
       [0.898278  , 0.81698951],
       [1.02243621, 1.11463433],
       [0.69067283, 1.20005908]])

array([[0.6361953 , 0.3177178 ],
       [0.82308877, 0.56081245],
       [0.14123245, 0.19634242],
       [0.3576443 , 0.60609402],
       [0.34718555, 0.69381497]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [282]:
Z = np.arange(10)
Z[(Z > 3) & (Z < 8)] *= -1 
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script?

In [315]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
del sum
print(sum(range(5),-1))

9
10
9


We can find the explanation for [here(The numpy.sum shadows the default sum function)](https://stackoverflow.com/questions/39552458/python-sum-has-a-different-result-after-importing-numpy).

#### 27. Consider an integer vector Z, which of these expressions are legal?

In [356]:
Z = [1]

In [357]:
Z**Z

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'list'

In [359]:
2 << Z >> 2 # 二进制左移右移

TypeError: unsupported operand type(s) for <<: 'int' and 'list'

In [360]:
Z <- Z

TypeError: bad operand type for unary -: 'list'

In [361]:
1j*Z

TypeError: can't multiply sequence by non-int of type 'complex'

In [362]:
Z/1/1

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [373]:
Z<Z>Z

False

In [374]:
[1] > [1,2]

False

#### 28. What are the result of the following expressions?

In [388]:
print(np.array(0) / np.array(0))

nan


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [389]:
print(np.array(0) // np.array(0))

0


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [391]:
print(np.array([np.nan]).astype(int).astype(float))
print(np.array([np.nan]).astype(int))

[-2.14748365e+09]
[-2147483648]


#### 29. How to round away from zero a float array ?

In [394]:
Z = np.random.uniform(-10,+10,10)
Z
print (np.copysign(np.ceil(np.abs(Z)), Z))

array([-3.02203316, -4.60144216,  7.91772436, -1.4381762 ,  9.29680094,
        3.26882996,  2.4339144 , -7.70508054,  8.98978517, -1.00175733])

[-4. -5.  8. -2. 10.  4.  3. -8.  9. -2.]


#### 30. How to find common values between two arrays?

In [423]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
print(np.array(list(set(Z1) & set(Z2))))

[1 2 6 8]
[8 1 2 6]


In [435]:
np.info(np.lib.arraysetops)

Set operations for arrays based on sorting.

:Contains:
  unique,
  isin,
  ediff1d,
  intersect1d,
  setxor1d,
  in1d,
  union1d,
  setdiff1d

:Notes:

For floating point arrays, inaccurate results may appear due to usual round-off
and floating point comparison issues.

Speed could be gained in some operations by an implementation of
sort(), that can provide directly the permutation vectors, avoiding
thus calls to argsort().

To do: Optionally return indices analogously to unique for all functions.

:Author: Robert Cimrman


#### 31. How to ignore all numpy warnings (not recommended)?

In [455]:
# Suicide mode on
defaults = np.seterr(all="ignore")
np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)
np.ones(1) // 0

with np.errstate(divide='ignore'): # did not change the global value of np.seterr
    Z = np.ones(1) / 0

array([inf])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in floor_divide
  import sys


array([nan])

#### 32. Is the following expressions true?

In [464]:
np.sqrt(-1) == np.emath.sqrt(-1) # nan != 1j

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [477]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday,today,tomorrow
tomorrow.astype(str)

(numpy.datetime64('2019-04-08'),
 numpy.datetime64('2019-04-09'),
 numpy.datetime64('2019-04-10'))

'2019-04-10'

#### 34. How to get all the dates corresponding to the month of July 2016?

In [19]:
Z = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [29]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out = B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods

In [31]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 0. 9. 9. 2. 3. 0. 0. 7. 0.]
[2. 0. 9. 9. 2. 3. 0. 0. 7. 0.]
[2. 0. 9. 9. 2. 3. 0. 0. 7. 0.]
[2 0 9 9 2 3 0 0 7 0]
[2. 0. 9. 9. 2. 3. 0. 0. 7. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [42]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [52]:
def generater():
    for x in range(10):
        yield x
Z = np.fromiter(generater(),dtype = int,count = -1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [58]:
Z = np.linspace(0,1,11,endpoint= False)
Z

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091])

#### 40. Create a random vector of size 10 and sort it

In [70]:
Z = np.random.random(10)
Z.sort()
Z

array([0.17339841, 0.1913219 , 0.25227679, 0.29840013, 0.45488701,
       0.72933392, 0.78999436, 0.80217177, 0.90527753, 0.9960705 ])

#### 41. How to sum a small array faster than np.sum?

In [ ]:
Z = np.arange(10)

In [82]:
%timeit np.add.reduce(Z)

721 ns ± 3.13 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [81]:
%timeit np.sum(Z)

1.78 µs ± 9.31 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [80]:
%timeit sum(Z)

1.22 µs ± 4.18 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 42. Consider two random array A and B, check if they are equal

In [83]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only)

In [84]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [94]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.89725745 0.88169785 0.47042005 0.98656533 0.98096369 0.7410089
 0.3331859  1.02365967 0.95154083 0.48306119]
[1.10201217 0.79968315 1.53428457 0.43535278 0.72163409 0.37882186
 0.61471999 0.49847286 0.84595987 1.45960655]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [113]:
Z = np.random.randint(0,10,size = (10))
Z[Z == Z.max()] = 0
Z
Z[Z.argmax()] = 0
Z

array([0, 1, 2, 0, 0, 0, 2, 7, 5, 6])

#### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [125]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),
                           np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [126]:
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [1]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array?

In [137]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [146]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

57


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [177]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z.shape)
print(Z)
print(Z['position']['x'])

(10,)
[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [263]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
print(X.shape)
X
print(np.sqrt(Z[:,0] - Z[:,0].T).shape)
print(np.sqrt((X-X.T)**2).shape)

(1, 10)
(10,)
(10, 10)


In [275]:
B = np.arange(10)
B.shape,B.T.shape,B - B.T

B = np.atleast_2d(B)
B.shape,B.T.shape,B - B.T # each element's result is filled by column

((1, 10), (10, 1), array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
        [-2, -1,  0,  1,  2,  3,  4,  5,  6,  7],
        [-3, -2, -1,  0,  1,  2,  3,  4,  5,  6],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-6, -5, -4, -3, -2, -1,  0,  1,  2,  3],
        [-7, -6, -5, -4, -3, -2, -1,  0,  1,  2],
        [-8, -7, -6, -5, -4, -3, -2, -1,  0,  1],
        [-9, -8, -7, -6, -5, -4, -3, -2, -1,  0]]))

In [225]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D,'\n')

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.75954735 0.11509653 0.63021642 0.68909134 0.86652869
  0.55161279 0.4100378  0.3705843  0.77933292]
 [0.75954735 0.         0.65069653 0.17470455 0.16268783 0.19175754
  0.60177072 0.47967938 0.64527374 0.13141625]
 [0.11509653 0.65069653 0.         0.5164072  0.57471721 0.76762361
  0.52199379 0.35060237 0.3595753  0.67898768]
 [0.63021642 0.17470455 0.5164072  0.         0.06277939 0.35827053
  0.60770217 0.43974621 0.59829948 0.27955378]
 [0.68909134 0.16268783 0.57471721 0.06277939 0.         0.35430453
  0.66198946 0.49950265 0.65945827 0.28574026]
 [0.86652869 0.19175754 0.76762361 0.35827053 0.35430453 0.
  0.57259545 0.51456414 0.66972676 0.09005889]
 [0.55161279 0.60177072 0.52199379 0.60770217 0.66198946 0.57259545
  0.         0.20236405 0.18778579 0.52256936]
 [0.4100378  0.47967938 0.35060237 0.43974621 0.49950265 0.51456414
  0.20236405 0.         0.16564423 0.44063262]
 [0.3705843  0.64527374 0.3595753  0.59829948 0.65945827 0.66972676
  0.18778579 0.16564

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [303]:
Z = np.arange(10, dtype=np.float32)
Z1 = Z.astype(np.int32,copy = True)
Z,Z1


(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [313]:
Z = np.arange(10, dtype=np.float32)
print(Z.astype(np.int32, copy = False).dtype)
print(Z.dtype)

int32
float32


In [312]:
Z = np.arange(10, dtype=np.float32)
print(Z.astype(np.int32, copy = True).dtype)
print(Z.dtype)

int32
float32


#### 54. How to read the following file?

In [319]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays?

In [331]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array

In [8]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [23]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [10]:
for x,y,z in it:
   print(y)

In [46]:
A = np.arange(12).reshape(3,4)
B = np.arange(12).reshape(3,4,order = 'F')

print(A)
for i in np.nditer(A,flags = ['f_index'],order = 'F'):
  print(i)
  
print(B)
for i in np.nditer(B,order = 'C'):
  print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
4
8
1
5
9
2
6
10
3
7
11
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
0
3
6
9
1
4
7
10
2
5
8
11


In [51]:
a = np.arange(6).reshape(2,3)
print(a)
for x in np.nditer(a, op_flags=['readwrite']):
     x[...] = x*2

a


[[0 1 2]
 [3 4 5]]


array([[ 0,  2,  4],
       [ 6,  8, 10]])

the speed of broadcast opeartion is faster than nditer

In [103]:
%%timeit -n 1000
a = np.arange(600).reshape(20,30)
for x,y in np.nditer([a,None]):
     y[...] = x*2

584 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [96]:
%%timeit -n 1000 
a = np.arange(600).reshape(20,30)
y=a*2

2.71 µs ± 296 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [106]:
a = np.arange(600).reshape(20,30)
it = np.nditer([a,None])
for x,y in it:
     y[...] = x*2 
it.operands[1]

array([[   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
          22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
          44,   46,   48,   50,   52,   54,   56,   58],
       [  60,   62,   64,   66,   68,   70,   72,   74,   76,   78,   80,
          82,   84,   86,   88,   90,   92,   94,   96,   98,  100,  102,
         104,  106,  108,  110,  112,  114,  116,  118],
       [ 120,  122,  124,  126,  128,  130,  132,  134,  136,  138,  140,
         142,  144,  146,  148,  150,  152,  154,  156,  158,  160,  162,
         164,  166,  168,  170,  172,  174,  176,  178],
       [ 180,  182,  184,  186,  188,  190,  192,  194,  196,  198,  200,
         202,  204,  206,  208,  210,  212,  214,  216,  218,  220,  222,
         224,  226,  228,  230,  232,  234,  236,  238],
       [ 240,  242,  244,  246,  248,  250,  252,  254,  256,  258,  260,
         262,  264,  266,  268,  270,  272,  274,  276,  278,  280,  282,
         284,  286,  288,  290, 

In [149]:
# try to print out the flag and value of the nditer object
a = np.arange(3)
b = np.arange(6).reshape(2,3)
for x, y in np.nditer([a,b]):
    print("%d:%d" % (x,y))
#     print("{0}:{1:.2f}".format(x,y))

0:0
1:1
2:2
0:3
1:4
2:5


We can use built-in function dir to check out the attribute of a instance of a object.

In [148]:
dir(it)
# import pprint 
# pprint.pprint(dir(it))

['__class__',
 '__copy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'copy',
 'debug_print',
 'dtypes',
 'enable_external_loop',
 'finished',
 'has_delayed_bufalloc',
 'has_index',
 'has_multi_index',
 'index',
 'iterationneedsapi',
 'iterindex',
 'iternext',
 'iterrange',
 'itersize',
 'itviews',
 'multi_index',
 'ndim',
 'nop',
 'operands',
 'remove_axis',
 'remove_multi_index',
 'reset',
 'shape',
 'value']


#### 63. Create an array class that has a name attribute (★★☆)

In [154]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name") # if there is no attribute:name, get the value of attribute:no name 

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [203]:
# Author: Brett Olsen

Z = np.ones(10,dtype = int)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[3 3 2 3 3 2 3 6 2 3]
[ 5  5  3  5  5  3  5 11  3  5]


In [208]:
Z = np.ones(10,dtype = int)
I = np.random.randint(0,len(Z),20)
Z,I,np.bincount(I, minlength=len(Z))

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([8, 0, 9, 2, 6, 0, 0, 9, 9, 0, 1, 7, 6, 7, 8, 9, 2, 3, 9, 3]),
 array([4, 1, 2, 2, 0, 0, 2, 2, 2, 5], dtype=int64))

In [224]:
unique, counts = np.unique(I, return_counts=True)
unique,counts

(array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 1, 2, 2, 2, 2, 2, 5], dtype=int64))

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [231]:
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X) # X is the weight of I
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [232]:
# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [242]:
I[...,1]

array([[1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0]], dtype=uint8)

In [245]:
np.arange(120).reshape(3,4,10)[...,3]

array([[  3,  13,  23,  33],
       [ 43,  53,  63,  73],
       [ 83,  93, 103, 113]])

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [247]:
A = np.random.randint(0,10,(3,4,5,6))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[135 130 137 131]
 [137 141 125 142]
 [138 117 115 123]]
[[135 130 137 131]
 [137 141 125 142]
 [138 117 115 123]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [251]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.42048181 0.61335776 0.52871067 0.4657742  0.47898425 0.56148675
 0.53094138 0.56535945 0.61987856 0.47616961]
0    0.420482
1    0.613358
2    0.528711
3    0.465774
4    0.478984
5    0.561487
6    0.530941
7    0.565359
8    0.619879
9    0.476170
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [272]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.63071144, 1.78678622, 0.95424471, 0.73346992, 1.1796638 ])

In [302]:
%%timeit 
np.diag(np.dot(A, B))

2.74 µs ± 48.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [301]:
%%timeit
np.sum(A * B.T, axis=1)

4.14 µs ± 80.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [299]:
%%timeit
# Faster version
np.einsum("ij,ji->i", A, B)

1.47 µs ± 3.87 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [305]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [309]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [318]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [327]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 74) ( 2, 89) (10, 68) (10, 76) (16, 39) (16, 45) (24, 44) (24, 88)
 (26, 70) (26, 95) (32, 53) (32, 90) (39, 45) (44, 88) (53, 90) (54, 59)
 (54, 95) (57, 73) (57, 77) (59, 95) (61, 61) (61, 66) (68, 76) (70, 95)
 (73, 77) (74, 89) (79, 82) (79, 87) (82, 87)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [347]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [348]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [457]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [460]:
def rolling2(Z,window):
    Z_index = np.repeat(np.arange(3).reshape(-1,3),len(Z)-window +1,axis = 0)
    j = 0
    for i in range(len(Z_index)):
        Z_index[i,:] += j 
        j += 1
    return Z[Z_index]

Z = rolling2(np.arange(10),3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [499]:
def rolling3(Z,window):
    Z_index = np.repeat(np.arange(3).reshape(-1,3),len(Z)-window +1,axis = 0) + np.arange(len(Z)-window +1)[:,np.newaxis]
    return Z[Z_index]

Z = rolling3(np.arange(10),3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [500]:
%%timeit
rolling3(np.arange(1000),3)

32.8 µs ± 424 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [503]:
%%timeit
rolling(np.arange(1000),3)

8.21 µs ± 500 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [520]:
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,5)
Z,np.logical_not(Z)

(array([1, 0, 1, 1, 1]), array([False,  True, False, False, False]))

In [522]:
Z = np.random.uniform(-1.0,1.0,5)
Z,np.negative(Z)

(array([ 0.17306923, -0.60237433,  0.01943256,  0.9063446 ,  0.09739419]),
 array([-0.17306923,  0.60237433, -0.01943256, -0.9063446 , -0.09739419]))

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [628]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-1e5,1e5,(10,2))
P1 = np.random.uniform(-1e5,1e5,(10,2))
p  = np.random.uniform(-1e5,1e5,( 1,2))
print(distance(P0, P1, p))

[13185.15632181 34330.08384784 98521.80757396  2448.27351111
 15146.23324505 20540.9279908  61888.98738512 24456.55079679
  6160.09705066 47566.39225878]


In [605]:
def distance2(P0, P1, p):
  T = P0 - P1 
  L = (T**2).sum(axis = 1)
  U = (P1[:,0] - P0[:,0])*p[:,1] - (P1[:,1] - P0[:,1])*p[:,0] + P0[:,0]*P1[:,1] - P0[:,1]*P1[:,0]
  D = np.sqrt(U**2 / L)
  return D

In [608]:
def distance3(P0, P1, p):
  T = P0 - P1 
  L = (T**2).sum(axis = 1)
  U = (P1[:,0] - P0[:,0])*p[:,1] - (P1[:,1] - P0[:,1])*p[:,0] + P0[:,0]*P1[:,1] - P0[:,1]*P1[:,0]
  return np.sqrt(U**2 / L)

In [619]:
%timeit -r 100 -n 10000 distance(P0, P1, p)

25.2 µs ± 961 ns per loop (mean ± std. dev. of 100 runs, 10000 loops each)


In [623]:
%timeit -r 1000 -n 10000 distance2(P0, P1, p)

19.4 µs ± 1.03 µs per loop (mean ± std. dev. of 1000 runs, 10000 loops each)


In [622]:
%timeit -r 1000 -n 10000 distance3(P0, P1, p)

18.3 µs ± 394 ns per loop (mean ± std. dev. of 1000 runs, 10000 loops each)


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [626]:
# Author: Italmassov Kuanysh
# np.set_printoptions(suppress=True)
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 8.32485907  8.58363388  0.358559    4.34081442  4.53340601  7.44986501
   1.26594716  1.75982135  8.34616132  5.88645008]
 [ 3.34145534  7.46521614 12.62375465  2.14765655  6.25127546  3.49063554
   9.42233316  2.91078183 13.17556572  5.73306578]
 [ 1.14999329  9.1048995  10.5509534   3.91806538  7.49427735  1.23139516
   9.44874263  4.23905235 13.89384953  3.53547393]
 [ 2.99483657  8.77315224 12.46545584  3.42407461  7.59629837  2.9835774
  10.56968768  4.25372499 14.48143504  5.37453332]
 [ 8.50350356  4.77482707  0.44788932  0.73890435  0.3169271   7.07112416
   3.02999536  2.39117998  3.92207974  6.02444665]
 [ 9.66605091 13.91476191  0.21025662  9.53653565 10.03376535  9.45044152
   6.00010573  7.24812141 13.70632044  7.27656091]
 [ 2.58441992  0.767505    5.21883607  3.64248057  2.57884777  1.02914396
   2.64189181  5.52351932  2.4611741   0.09320496]
 [ 1.74851798  0.61733693  9.81708648  4.20501498  1.65035243  2.99635415
   0.6765805   4.80951453  4.55640023  4.21958359]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [681]:
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (4,5)

In [682]:
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

In [683]:
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

In [684]:
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

In [685]:
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 0 4 3 5 5 0 5 9 6]
 [4 1 0 3 7 1 1 2 3 6]
 [1 4 9 8 0 2 1 8 7 4]
 [1 1 4 8 1 5 1 7 9 9]
 [5 3 3 3 2 7 4 7 9 9]
 [0 2 7 3 1 5 8 8 6 3]
 [2 1 2 4 1 4 1 4 4 6]
 [2 8 1 9 5 8 5 5 6 2]
 [2 7 1 0 9 3 3 7 9 0]
 [4 2 2 2 2 1 4 0 1 8]]
[[8 0 2 1 8]
 [8 1 5 1 7]
 [3 2 7 4 7]
 [3 1 5 8 8]
 [4 1 4 1 4]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [ ]:
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

#### 82. Compute a matrix rank (★★★)

In [687]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [706]:
np.allclose(np.dot(np.dot(U,np.diag(S)),V),Z)

True

In [702]:
np.allclose(U @ np.diag(S) @ V,Z)

True

#### 83. How to find the most frequent value in an array?

In [767]:
Z = np.random.randint(0,10,50)
G = np.bincount(Z)
H = np.arange(len(G))
H[G == max(G)],G,H

(array([9]),
 array([5, 6, 3, 5, 4, 6, 6, 5, 3, 7], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [768]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 4]
   [3 1 4]
   [0 0 1]]

  [[0 4 0]
   [1 4 3]
   [0 1 1]]

  [[4 0 2]
   [4 3 3]
   [1 1 2]]

  [[0 2 1]
   [3 3 1]
   [1 2 3]]

  [[2 1 0]
   [3 1 4]
   [2 3 0]]

  [[1 0 3]
   [1 4 1]
   [3 0 2]]

  [[0 3 2]
   [4 1 3]
   [0 2 3]]

  [[3 2 4]
   [1 3 3]
   [2 3 1]]]


 [[[3 1 4]
   [0 0 1]
   [2 1 1]]

  [[1 4 3]
   [0 1 1]
   [1 1 2]]

  [[4 3 3]
   [1 1 2]
   [1 2 0]]

  [[3 3 1]
   [1 2 3]
   [2 0 4]]

  [[3 1 4]
   [2 3 0]
   [0 4 4]]

  [[1 4 1]
   [3 0 2]
   [4 4 3]]

  [[4 1 3]
   [0 2 3]
   [4 3 4]]

  [[1 3 3]
   [2 3 1]
   [3 4 0]]]


 [[[0 0 1]
   [2 1 1]
   [2 2 3]]

  [[0 1 1]
   [1 1 2]
   [2 3 1]]

  [[1 1 2]
   [1 2 0]
   [3 1 0]]

  [[1 2 3]
   [2 0 4]
   [1 0 2]]

  [[2 3 0]
   [0 4 4]
   [0 2 0]]

  [[3 0 2]
   [4 4 3]
   [2 0 3]]

  [[0 2 3]
   [4 3 4]
   [0 3 2]]

  [[2 3 1]
   [3 4 0]
   [3 2 1]]]


 [[[2 1 1]
   [2 2 3]
   [1 1 0]]

  [[1 1 2]
   [2 3 1]
   [1 0 2]]

  [[1 2 0]
   [3 1 0]
   [0 2 3]]

  [[2 0 4]
   [1 0 2]
   [2 3 0]]

  [[0 4 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [769]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1  9 10  3  8]
 [ 9  1 10 15  7]
 [10 10  2 42  3]
 [ 3 15 42  6  6]
 [ 8  7  3  6  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [773]:
# Author: Stefan van der Walt

p, n = 2, 5
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[10.]
 [10.]
 [10.]
 [10.]
 [10.]]


In [776]:
M.shape,V.shape

((2, 5, 5), (2, 5, 1))

In [777]:
np.tensordot(M, V, axes=[[1, 2], [0, 1]])

ValueError: shape-mismatch for sum

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [778]:
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [786]:
# Author: Ryan G.

x = np.random.randint(50)

In [788]:
%timeit np.power(x,3)

1.11 µs ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [789]:
%timeit x*x*x

93.7 ns ± 1.76 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [787]:
%timeit np.einsum('i,i,i->i',x,x,x)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

In [346]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0